#!/usr/bin/env python3
"""
Script to will get the current weather from https://openweathermap.org/api
The script reads no CLI arguments. It is parametrized via the following environment
variables: OWM_API_KEY, OWM_CITY. It prints to stdout.
"""
import os
import requests

def get_weather(api_key, city):
    url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric"
    response = requests.get(url, verify="/etc/ssl/certs/ca-certificates.crt")
    weather_data = response.json()

    if response.status_code == 200:
        temperature = weather_data['main']['temp']
        humidity = weather_data['main']['humidity']
        description = weather_data['weather'][0]['description']

        print(f"""city="{city}", description="{description}", temp={temperature}, humidity={humidity}""")

    else:
        print(f"Failed to retrieve weather data. Response code: {response.status_code}")

def main():
    api_key = os.getenv('OWM_API_KEY')
    city = os.getenv('OWM_CITY')

    if api_key is None or city is None:
        print("Please set the OWM_API_KEY and OWM_CITY environment variables.")
        return

    get_weather(api_key, city)

if __name__ == '__main__':
    main()