apiVersion: v1
kind: PersistentVolume
metadata:
  name: scanner-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/scanner/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanner-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scanner
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 1000
          volumes:
          - name: scanner-volume
            persistentVolumeClaim:
              claimName: scanner-pv-claim
          containers:
          - name: scanner
            image: docker.io/etemctl/scanner:1.0
            args: ["192.168.0.0/24"]
            volumeMounts:
            - mountPath: "/app/data/"
              name: scanner-volume
          restartPolicy: OnFailure
